# Generated by Django 3.2.16 on 2024-09-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='birthday',
            new_name='post',
        ),
    ]
